# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: check-ast
  - repo: local
    hooks:
      - id: lint
        name: lint python source files
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true
      - id: mypy
        name: perform type-checking
        entry: make mypy
        language: system
        pass_filenames: false
        always_run: true
      - id: poetry-check
        name: validate the structure of the pyproject.toml
        entry: poetry check
        language: system
        pass_filenames: false
        always_run: true
      - id: poetry-lock-check
        name: verify that poetry.lock is consistent with pyproject.toml
        entry: poetry lock --check
        language: system
        pass_filenames: false
        always_run: true
